
### region list
GET http://localhost:8090/regions

### exception 테스트
GET http://localhost:8090/exception

### region create
POST http://localhost:8090/regions2
Content-Type: application/json

{
  "region": "seoul",
  "dataType": 1,
  "dateTime": "20230526"
}